---
swagger: "2.0"
info:
  version: "2021-01-28T03:33:09Z"
  title: "goldenApi"
host: "i0btc4oss2.execute-api.us-west-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "order"
        in: "query"
        required: false
        type: "string"
      - name: "query"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /query1:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /query2/{proxy+}:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      parameters:
      - name: "order"
        in: "query"
        required: true
        type: "string"
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      responses: {}
  /query3/{proxy+}:
    x-amazon-apigateway-any-method:
      produces:
      - "application/json"
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        type: "string"
      responses: {}
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
